Add cli flag to only export completed tasks
wayneashleyberry/wunderlist-cli pull request #104
Opened 2016-11-26 11:02 UTC by adius

2016-11-26 13:11 UTC, Thor77 commented
I don't really see the usecase for that in the export-subcommand atm but the code lgtm, can you elaborate why you think this feature is useful?

2016-11-26 13:13 UTC, Thor77 requested changes
Don't add the `completed`-option to endpoints not supporting it.

2016-11-26 13:13 UTC, Thor77 commented on wunderline-export.js
> +        api({url: '/notes', qs: queryOptions}, function (err, res, body) {
`completed` is not a valid option for `/notes`

2016-11-26 13:13 UTC, Thor77 commented on wunderline-export.js
> +        api({url: '/files', qs: queryOptions}, function (err, res, body) {
`completed` is not a valid option for `/files`

2016-11-26 13:54 UTC, adius commented on wunderline-export.js
> +        api({url: '/notes', qs: queryOptions}, function (err, res, body) {
Oh … good catch!

2016-11-26 13:57 UTC, adius commented
> I don't really see the usecase for that in the export-subcommand

😳 I was really surprised that it only exported the open tasks.
If I export data from a program I expect it to export *all* data it has.
So I actually I would per default export the open *and* the completed tasks
and add `--open` and `--completed` flags if one wants to only export a subset.

2016-11-26 14:00 UTC, adius commented
If you export your emails from your email app you don't expect it to only export your unread emails either, would you?  ^^

2016-11-26 19:13 UTC, Thor77 commented
> So I actually I would per default export the open and the completed tasks
and add --open and --completed flags if one wants to only export a subset.

Yeah, that sounds like the right way to do it, feel free to open another PR for the additional flag and changing the default output (or include it into this one).
Therefore I will merge your PR once you fix the two things I mentioned in my review.

2016-12-10 22:56 UTC, Thor77 commented
Anything I can help you with to get this PR ready for merge @adius ?

2016-12-11 16:43 UTC, adius commented
Not sure if this is the most beautiful solution,
but the limited Wunderlist API doesn't make things easy…

2016-12-12 20:57 UTC, Thor77 commented
Thanks for taking a look again and implementing the additional flag right away.
I'm not sure about changing the default, though. What do you think, @wayneashleyberry ?

2016-12-13 07:53 UTC, wayneashleyberry commented
From my side I'd leave these filters out of the `export` command. Export was only ever intended to give you _all_ of your data, what you then choose to do with it is up to you.

There are many tools available such as [jid](https://github.com/simeji/jid) and [jq](https://stedolan.github.io/jq/) which provide excellent filtering for json.

Here is an example of filtering only your starred tasks from a full export using jq.

```sh
wunderline export | jq '.data.lists[].tasks[] | select(.starred == true)'
```

2017-01-10 10:16 UTC, wayneashleyberry commented
Hey @adius, I'm going to close this pull request. I appreciate you pointing out that completed tasks weren't being exported, but I've opted for a simpler implementation.

2017-01-10 10:16 UTC, closed without merging

2017-01-10 10:34 UTC, wayneashleyberry commented
Merged in https://github.com/wayneashleyberry/wunderline/pull/105 and published as [v4.4.4](https://github.com/wayneashleyberry/wunderline/releases/tag/v4.4.4).

Please let me know if you're happy @adius. I've also updated the [readme](https://github.com/wayneashleyberry/wunderline#export) with examples for filtering out the exported data.

2017-01-21 21:53 UTC, adius commented
Looks good, Thanks!